import React from 'react';
import { Container, Typography } from '@material-ui/core';

const PrivacyPolicy = () => {
  return (
    <Container maxWidth="md" className="py-8">
      <Typography variant="h3" component="h1" className="mb-6">TERMS & CONDITIONS</Typography>
      <Typography variant="h2" component="h1" className="mb-6">General Terms</Typography>
      <Typography variant="body1" className="mb-4">
      By accessing and placing an order with Loumni , you confirm that you are in agreement with and bound by
    the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire
    website and any email or other type of communication between you and Loumni .
    Under no circumstances shall Loumni team be liable for any direct, indirect, special, incidental or
    consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the
    inability to use, the materials on this site, even if Loumni team or an authorized representative has been
    advised of the possibility of such damages. If your use of materials from this site results in the need for
    servicing, repair or correction of equipment or data, you assume any costs thereof.
    Loumni will not be responsible for any outcome that may occur during the course of usage of our resources.
    We reserve the rights to change prices and revise the resources usage policy in any moment.
      </Typography>
      <Typography variant="h2" className="mb-4">
      License</Typography>
      <Typography> Loumni grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use
        the app strictly in accordance with the terms of this Agreement.
        These Terms & Conditions are a contract between you and Loumni (referred to in these Terms & Conditions
        as "Loumni ", "us", "we" or "our"), the provider of the Loumni website and the services accessible from the
        Loumni website (which are collectively referred to in these Terms & Conditions as the "Loumni Service").
        You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms &
        Conditions, please do not use the Loumni Service. In these Terms & Conditions, "you" refers both to you as
        an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the
        right to cancel your account or block access to your account without notice.</Typography> 
   



    <Typography variant="h2" className="mb-4 mt-20"> Definitions and key terms </Typography>

    <Typography>To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are
referenced, are strictly defined as:
</Typography>
<Typography>● Cookie: small amount of data generated by a website and saved by your web browser. It is used to
identify your browser, provide analytics, remember information about you such as your language
preference or login information.</Typography>
<Typography>● Company: when this terms mention “Company,” “we,” “us,” or “our,” it refers to Loumni Integrity Service
, (No.9 Kafanchan Close, Abuja), that is responsible for your information under this Terms & Conditions. </Typography>
<Typography>● Country: where Loumni or the owners/founders of Loumni are based, in this case is Nigeria</Typography>
<Typography>● Device: any internet connected device such as a phone, tablet, computer or any other device that can
be used to visit Loumni and use the services</Typography>
<Typography>● Service: refers to the service provided by Loumni as described in the relative terms (if available) and on
this platform.
</Typography>
<Typography>● Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and
others who provide our content or whose products or services we think may interest you.</Typography>
<Typography>● App/Application: Loumni app, refers to the SOFTWARE PRODUCT identified above.</Typography>
<Typography>● You: a person or entity that is registered with Loumni to use the Services.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Restrictions</Typography>

<Typography>You agree not to, and you will not permit others to</Typography> 
<Typography>● License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise
commercially exploit the app or make the platform available to any third party</Typography> 
<Typography>● Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part
of the app.</Typography> 
<Typography>● Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of
Loumni or its affiliates, partners, suppliers or the licensors of the app.</Typography> 


<Typography variant="h2" className="mb-4 mt-20">Payments</Typography>

<Typography> If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for
the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or
charge is due and payable. Unless otherwise indicated in an order form, you must provide Loumni with a
valid credit card (Visa, MasterCard, or any other issuer accepted by us) (“Payment Provider”) as a condition
to signing up for the Premium plan. Your Payment Provider agreement governs your use of the designated
credit card account, and you must refer to that agreement and not these Terms to determine your rights and
liabilities with respect to your Payment Provider. By providing Loumni with your credit card number and
associated payment information, you agree that Loumni is authorized to verify information immediately, and
subsequently invoice your account for all fees and charges due and payable to Loumni hereunder and that
no additional notice or consent is required. You agree to immediately notify Loumni of any change in your
billing address or the credit card used for payment hereunder. Loumni reserves the right at any time to
change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to
your organization’s administrator(s).
Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall
be the responsibility of and paid for by you.
No contract will exist between you and Loumni for the Service until Loumni accepts your order by a
confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.
You are responsible for any third-party fees that you may incur when using the Service.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Return and Refund Policy</Typography>

<Typography>Thanks for shopping at Loumni . We appreciate the fact that you like to buy the stuff we build. We also want
to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our
products.
page 3/9
As with any shopping experience, there are terms and conditions that apply to transactions at Loumni . We’ll
be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a
purchase at Loumni , you agree to the terms along with Loumni ’s Privacy Policy.
If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to
contact us and we will discuss any of the issues you are going through with our product</Typography>

<Typography variant="h2" className="mb-4 mt-20">Term and Termination
</Typography>

<Typography> This Agreement shall remain in effect until terminated by you or Loumni .
Loumni may, in its sole discretion, at any time and for any or no reason, suspend or terminate this
page 5/9
Agreement with or without prior notice.
This Agreement will terminate immediately, without prior notice from Loumni , in the event that you fail to
comply with any provision of this Agreement. You may also terminate this Agreement by deleting the app
and all copies thereof from your computer.
Upon termination of this Agreement, you shall cease all use of the app and delete all copies of the app from
your computer.
Termination of this Agreement will not limit any of Loumni 's rights or remedies at law or in equity in case of
breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.
 </Typography>

 <Typography variant="h2" className="mb-4 mt-20">Copyright Infringement Notice
</Typography>

<Typography>If you are a copyright owner or such owner’s agent and believe any material on our app constitutes an
infringement on your copyright, please contact us setting forth the following information: (a) a physical or
electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the
material that is claimed to be infringing; (c) your contact information, including your address, telephone
number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not
authorized by the copyright owners; and (e) the a statement that the information in the notification is
accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Indemnification
</Typography>

<Typography>You agree to indemnify and hold Loumni and its parents, subsidiaries, affiliates, officers, employees, agents,
partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due
to or arising out of your: (a) use of the app; (b) violation of this Agreement or any law or regulation; or (c)
violation of any right of a third party.
</Typography>



<Typography variant="h2" className="mb-4 mt-20">No Warranties</Typography>
<Typography>The app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of
any kind. To the maximum extent permitted under applicable law, Loumni , on its own behalf and on behalf
of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties,
whether express, implied, statutory or otherwise, with respect to the app, including all implied warranties of
merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out
of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing,
Loumni provides no warranty or undertaking, and makes no representation of any kind that the app will meet
your requirements, achieve any intended results, be compatible or work with any other software, apps,
systems or services, operate without interruption, meet any performance or reliability standards or be error
free or that any errors or defects can or will be corrected.
Without limiting the foregoing, neither Loumni nor any Loumni 's provider makes any representation or
warranty of any kind, express or implied: (i) as to the operation or availability of the app, or the information,
content, and materials or products included thereon; (ii) that the app will be uninterrupted or error-free; (iii) as
to the accuracy, reliability, or currency of any information or content provided through the app; or (iv) that the
app, its servers, the content, or e-mails sent from or on behalf of Loumni are free of viruses, scripts, trojan
horses, worms, malware, timebombs or other harmful components.
Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the
page 6/9
applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not
apply to you.</Typography>


<Typography variant="h2" className="mb-4 mt-20">Severability
</Typography>
<Typography>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and
interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable
law and the remaining provisions will continue in full force and effect.
This Agreement, together with the Privacy Policy and any other legal notices published by Loumni on the
Services, shall constitute the entire agreement between you and Loumni concerning the Services. If any
provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such
provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full
force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of
such term or any other term, and Loumni ’s failure to assert any right or provision under this Agreement shall
not constitute a waiver of such right or provision. YOU AND Loumni AGREE THAT ANY CAUSE OF
ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1)
YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS
PERMANENTLY BARRED.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Waiver</Typography>
<Typography>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this
Agreement shall not effect a party's ability to exercise such right or require such performance at any time
thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.
No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under
this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any
right or power under this Agreement preclude further exercise of that or any other right granted herein. In the
event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this
Agreement shall govern.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Amendments to this Agreement
</Typography>
<Typography>Loumni reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision
is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a
material change will be determined at our sole discretion.
By continuing to access or use our app after any revisions become effective, you agree to be bound by the
revised terms. If you do not agree to the new terms, you are no longer authorized to use Loumni .
</Typography>
<Typography variant="h2" className="mb-4 mt-20">Entire Agreement</Typography>
<Typography>The Agreement constitutes the entire agreement between you and Loumni regarding your use of the app
and supersedes all prior and contemporaneous written or oral agreements between you and Loumni .
You may be subject to additional terms and conditions that apply when you use or purchase other Loumni 's
services, which Loumni will provide to you at the time of such use or purchase.
</Typography>
<Typography > <Typography variant="h2" className="mb-4 mt-20">Updates to Our Terms</Typography> </Typography>
<Typography>We may change our Service and policies, and we may need to make changes to these Terms so that they
accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example,
through our Service) before we make changes to these Terms and give you an opportunity to review them
before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms.
If you do not want to agree to these or any updated Terms, you can delete your account.</Typography>
<Typography variant="h2" className="mb-4 mt-20">Intellectual Property</Typography>
<Typography>The app and its entire contents, features and functionality (including but not limited to all information,
software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are
owned by Loumni , its licensors or other providers of such material and are protected by Nigeria and
international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights
laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole
or in part, without the express prior written permission of Loumni , unless and except as is expressly
provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Agreement to Arbitrate</Typography>
<Typography>This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS
FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR
OR Loumni ’s INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other
controversy between you and Loumni concerning the Services or this agreement, whether in contract,
warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the
broadest possible meaning allowable under law</Typography>

<Typography variant="h2" className="mb-4 mt-20">Notice of Disput</Typography>
<Typography>In the event of a dispute, you or Loumni must give the other a Notice of Dispute, which is a written statement
that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the
dispute, and the relief requested. You must send any Notice of Dispute via email to:
loumni2024@gmail.com. Loumni will send any Notice of Dispute to you by mail to your address if we have it,
or otherwise to your email address. You and Loumni will attempt to resolve any dispute through informal
negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or
Loumni may commence arbitration.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Binding Arbitration</Typography>
<Typography>If you and Loumni don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute
will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to
litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute
shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American
Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of
competent jurisdiction, as necessary to protect the party’s rights or property pending the completion of
arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing
party shall be borne by the non-prevailing party.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Submissions and Privacy</Typography>
<Typography>In the event that you submit or post any ideas, creative suggestions, designs, photographs, information,
advertisements, data or proposals, including ideas for new or improved products, services, features,
technologies or promotions, you expressly agree that such submissions will automatically be treated as
non-confidential and non-proprietary and will become the sole property of Loumni without any compensation
or credit to you whatsoever. Loumni and its affiliates shall have no obligations with respect to such
submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any
medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and
services using such ideas.</Typography>


<Typography variant="h2" className="mb-4 mt-20">Promotions</Typography>
<Typography>Loumni may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”)
that require you to submit material or information concerning yourself. Please note that all Promotions may
be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age
and geographic location. You are responsible to read all Promotions rules to determine whether or not you
are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all
Promotions Rules.
Additional terms and conditions may apply to purchases of goods or services on or through the Services,
which terms and conditions are made a part of this Agreement by this reference.</Typography>

<Typography variant="h2" className="mb-4 mt-20">Typographical Errors
</Typography>
<Typography>In the event a product and/or service is listed at an incorrect price or with incorrect information due to
typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or
service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not
the order has been confirmed and your credit card charged. If your credit card has already been charged for
the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or
page 9/9
other payment account in the amount of the charge.</Typography>



<Typography variant="h2" className="mb-4 mt-20">Miscellaneous</Typography>
<Typography>If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions
to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any
waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an
authorized representative of Loumni . Loumni will be entitled to injunctive or other equitable relief (without the
obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Loumni
operates and controls the Loumni Service from its offices in Nigeria . The Service is not intended for
distribution to or use by any person or entity in any jurisdiction or country where such distribution or use
would be contrary to law or regulation. Accordingly, those persons who choose to access the Loumni Service
from other locations do so on their own initiative and are solely responsible for compliance with local laws, if
and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate the
Loumni Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between
you and Loumni concerning its subject matter, and cannot be changed or modified by you. The section
headings used in this Agreement are for convenience only and will not be given any legal import.
</Typography>

<Typography variant="h2" className="mb-4 mt-20">Disclaimer</Typography>
<Typography>Loumni is not responsible for any content, code or any other imprecision.
Loumni does not provide warranties or guarantees.
In no event shall Loumni be liable for any special, direct, indirect, consequential, or incidental damages or
any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in
connection with the use of the Service or the contents of the Service. The Company reserves the right to
make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
The Loumni Service and its contents are provided "as is" and "as available" without any warranty or
representations of any kind, whether express or implied. Loumni is a distributor and not a publisher of the
content supplied by third parties; as such, Loumni exercises no editorial control over such content and
makes no warranty or representation as to the accuracy, reliability or currency of any information, content,
service or merchandise provided through or accessible via the Loumni Service. Without limiting the
foregoing, Loumni specifically disclaims all warranties and representations in any content transmitted on or in
connection with the Loumni Service or on sites that may appear as links on the Loumni Service, or in the
products provided as a part of, or otherwise in connection with, the Loumni Service, including without
limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party
rights. No oral advice or written information given by Loumni or any of its affiliates, employees, officers,
directors, agents, or the like will create a warranty. Price and availability information is subject to change
without notice. Without limiting the foregoing, Loumni does not warrant that the Loumni Service will be
uninterrupted, uncorrupted, timely, or error-free.</Typography>


<Typography variant="h2" className="mb-4 mt-20">Contact Us</Typography>
<Typography>Don't hesitate to contact us if you have any questions.
● Via Email: loumni2024@gmail.com</Typography>


      
      
    </Container>
  );
};

export default PrivacyPolicy;
